[package]
name = "renovate-12334-pr-multiple-updates-one-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.12.0"
tokio-test = "0.4.2"
seahash = "4.0.1"
